USE [GTI]
GO

/****** Object:  Table [dbo].[CategoriaProduto]    Script Date: 16/08/2022 18:53:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CategoriaProduto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_CategoriaProduto] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


